name: Close wontfix issues

on:
  issues:
    types: [labeled]

jobs:
  close-wontfix:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'wontfix'
    steps:
      - name: Close issue
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "Automatically closed because 'wontfix' label was added."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}